export const ERROR_CODES = {
  PROVIDER_NOT_CONFIGURED: 'PROVIDER_NOT_CONFIGURED',
  MODEL_OUTPUT_INVALID_JSON: 'MODEL_OUTPUT_INVALID_JSON',
  MODEL_OUTPUT_SCHEMA_INVALID: 'MODEL_OUTPUT_SCHEMA_INVALID',
  MODEL_REQUEST_FAILED: 'MODEL_REQUEST_FAILED',
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_ARGS_INVALID: 'TOOL_ARGS_INVALID',
  TOOL_RESULT_INVALID: 'TOOL_RESULT_INVALID',
  TOOL_EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  USER_DENIED_APPROVAL: 'USER_DENIED_APPROVAL',
  MAX_STEPS_EXCEEDED: 'MAX_STEPS_EXCEEDED',
  REF_NOT_FOUND: 'REF_NOT_FOUND',
  REF_STALE: 'REF_STALE',
  CONTENT_SCRIPT_UNAVAILABLE: 'CONTENT_SCRIPT_UNAVAILABLE',
  OBSERVATION_BUDGET_EXCEEDED: 'OBSERVATION_BUDGET_EXCEEDED',
  OBSERVATION_FAILED: 'OBSERVATION_FAILED',
  PROVIDER_ENDPOINT_UNAVAILABLE: 'PROVIDER_ENDPOINT_UNAVAILABLE'
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
