export const ERROR_CODE_DEFINITIONS = [
  { number: 0, code: 'OK', description: '成功' },
  { number: 1000, code: 'PROVIDER_NOT_CONFIGURED', description: '模型 provider 未配置' },
  { number: 1001, code: 'PROVIDER_ENDPOINT_UNAVAILABLE', description: '模型 provider endpoint 不可用' },
  { number: 1100, code: 'MODEL_REQUEST_FAILED', description: '模型请求失败' },
  { number: 1200, code: 'MODEL_OUTPUT_INVALID', description: '模型输出不符合 Agent 决策契约' },
  { number: 1201, code: 'MODEL_OUTPUT_INVALID_JSON', description: '模型输出不是有效 JSON' },
  { number: 1202, code: 'MODEL_OUTPUT_SCHEMA_INVALID', description: '模型输出 schema 校验失败' },
  { number: 2000, code: 'TOOL_NOT_FOUND', description: '工具不存在' },
  { number: 2001, code: 'TOOL_ARGS_INVALID', description: '工具参数无效' },
  { number: 2002, code: 'TOOL_RESULT_INVALID', description: '工具结果无效' },
  { number: 2003, code: 'TOOL_EXECUTION_FAILED', description: '工具执行失败' },
  { number: 2004, code: 'TOOL_MODE_NOT_ALLOWED', description: '当前 Run Mode 不允许使用该工具' },
  { number: 2100, code: 'AGENT_FINISH', description: 'Agent 正常结束' },
  { number: 2101, code: 'AGENT_FAIL', description: 'Agent 失败结束' },
  { number: 2102, code: 'ASK_USER_REQUIRED', description: 'Agent 需要用户输入' },
  { number: 2200, code: 'APPROVAL_REQUIRED', description: '需要审批' },
  { number: 2201, code: 'USER_DENIED_APPROVAL', description: '用户拒绝审批' },
  { number: 2202, code: 'APPROVAL_REQUEST_NOT_FOUND', description: '审批请求不存在' },
  { number: 2203, code: 'APPROVAL_REQUEST_NOT_PENDING', description: '审批请求不处于待处理状态' },
  { number: 2300, code: 'MAX_STEPS_EXCEEDED', description: '超过最大步骤数' },
  { number: 3000, code: 'RUNTIME_UNAVAILABLE', description: '扩展 runtime 不可用' },
  { number: 3001, code: 'RUNTIME_RESPONSE_INVALID', description: '扩展 runtime 响应无效' },
  { number: 3002, code: 'RUNTIME_MESSAGE_INVALID', description: '扩展 runtime 消息无效' },
  { number: 3003, code: 'RUN_CANCELLED', description: '运行已被用户取消' },
  { number: 3100, code: 'CONTENT_SCRIPT_UNAVAILABLE', description: 'content script 不可用' },
  { number: 3200, code: 'OBSERVATION_FAILED', description: '页面观察失败' },
  { number: 3201, code: 'OBSERVATION_BUDGET_EXCEEDED', description: '页面观察超过预算' },
  { number: 3300, code: 'REF_NOT_FOUND', description: 'Ref 不存在' },
  { number: 3301, code: 'REF_STALE', description: 'Ref 已失效' },
  { number: 3302, code: 'FRAME_NOT_FOUND', description: 'Frame 不存在' },
  { number: 3303, code: 'FRAME_REF_INVALID', description: 'iframe ref 格式无效' },
  { number: 3304, code: 'FRAME_REF_MISMATCH', description: 'iframe ref 与目标 frame 不匹配' },
  { number: 3305, code: 'PAGE_CHANGED', description: '页面结构已变更，需重新观察' },
  { number: 3306, code: 'ELEMENT_NOT_FOUND', description: '目标 DOM 元素不存在，需查找替代元素' },
  { number: 3307, code: 'IFRAME_ID_INVALID', description: 'iframeId 格式无效' },
  { number: 3400, code: 'ELEMENT_STATE_UNREADABLE', description: '元素状态不可读' },
  { number: 3401, code: 'ELEMENT_NOT_ACTIONABLE', description: '元素不可执行目标动作' },
  { number: 3402, code: 'IFRAME_ACTION_UNAUTHORIZED', description: 'iframe 动作未通过 runtime 授权' },
  { number: 3403, code: 'ELEMENT_DISABLED', description: '元素处于禁用状态' },
  { number: 3404, code: 'ACTION_TARGET_MISMATCH', description: '动作目标类型不匹配' },
  { number: 3405, code: 'FORM_ACTION_UNAUTHORIZED', description: '表单动作未通过 runtime 授权' },
  { number: 3500, code: 'FIELD_LABEL_MISSING', description: '字段 label 缺失' },
  { number: 3501, code: 'FORM_SUBMIT_NOT_FOUND', description: '未找到表单提交控件' },
  { number: 3502, code: 'FORM_FIELDS_UNAVAILABLE', description: '表单字段快照不可用' },
  { number: 3503, code: 'FIELD_SENSITIVE_SKIPPED', description: '敏感字段已跳过填写' },
  { number: 3504, code: 'FIELD_UNSUPPORTED_FILE_UPLOAD', description: '不支持文件上传字段' },
  { number: 3505, code: 'FIELD_UNSAFE_HIDDEN', description: '隐藏字段不安全已跳过' },
  { number: 3506, code: 'FIELD_HONEYPOT_CANDIDATE', description: '疑似蜜罐字段已跳过' },
  { number: 3507, code: 'FORM_VERIFY_FAILED', description: '表单验证未通过' },
  { number: 3508, code: 'SUBMIT_APPROVAL_DENIED', description: '提交审批被拒绝' },
  { number: 3509, code: 'SUBMIT_RESULT_UNKNOWN', description: '提交结果无法判定' },
  { number: 3510, code: 'NATIVE_DIALOG_UNSUPPORTED', description: '不支持原生 alert/confirm/prompt' },
  { number: 3511, code: 'FILL_RETRY_EXHAUSTED', description: '填写重试已耗尽' },
  { number: 3512, code: 'FIELD_NOT_WRITABLE', description: '字段不可写' },
  { number: 3513, code: 'FIELD_NOT_VISIBLE', description: '字段不可见' },
  { number: 3514, code: 'APPROVAL_CONTEXT_STALE', description: '审批上下文已过期，页面状态已变化' },
  { number: 3514, code: 'CROSS_FORM_FILL_REJECTED', description: '跨表单批量填写已拒绝' },
  { number: 3515, code: 'SUBMIT_DISABLED', description: '提交按钮处于禁用状态' },
  { number: 3516, code: 'APPROVAL_CONTEXT_STALE', description: '审批上下文已过期，需要重新验证' },
  { number: 3517, code: 'SUBMIT_TARGET_NOT_READY', description: '提交目标当前不可用' }
] as const;

export const ERROR_CODES = {
  OK: 'OK',
  PROVIDER_NOT_CONFIGURED: 'PROVIDER_NOT_CONFIGURED',
  PROVIDER_ENDPOINT_UNAVAILABLE: 'PROVIDER_ENDPOINT_UNAVAILABLE',
  MODEL_REQUEST_FAILED: 'MODEL_REQUEST_FAILED',
  MODEL_OUTPUT_INVALID: 'MODEL_OUTPUT_INVALID',
  MODEL_OUTPUT_INVALID_JSON: 'MODEL_OUTPUT_INVALID_JSON',
  MODEL_OUTPUT_SCHEMA_INVALID: 'MODEL_OUTPUT_SCHEMA_INVALID',
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_ARGS_INVALID: 'TOOL_ARGS_INVALID',
  TOOL_RESULT_INVALID: 'TOOL_RESULT_INVALID',
  TOOL_EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
  TOOL_MODE_NOT_ALLOWED: 'TOOL_MODE_NOT_ALLOWED',
  AGENT_FINISH: 'AGENT_FINISH',
  AGENT_FAIL: 'AGENT_FAIL',
  ASK_USER_REQUIRED: 'ASK_USER_REQUIRED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  USER_DENIED_APPROVAL: 'USER_DENIED_APPROVAL',
  APPROVAL_REQUEST_NOT_FOUND: 'APPROVAL_REQUEST_NOT_FOUND',
  APPROVAL_REQUEST_NOT_PENDING: 'APPROVAL_REQUEST_NOT_PENDING',
  MAX_STEPS_EXCEEDED: 'MAX_STEPS_EXCEEDED',
  RUNTIME_UNAVAILABLE: 'RUNTIME_UNAVAILABLE',
  RUNTIME_RESPONSE_INVALID: 'RUNTIME_RESPONSE_INVALID',
  RUNTIME_MESSAGE_INVALID: 'RUNTIME_MESSAGE_INVALID',
  RUN_CANCELLED: 'RUN_CANCELLED',
  CONTENT_SCRIPT_UNAVAILABLE: 'CONTENT_SCRIPT_UNAVAILABLE',
  OBSERVATION_FAILED: 'OBSERVATION_FAILED',
  OBSERVATION_BUDGET_EXCEEDED: 'OBSERVATION_BUDGET_EXCEEDED',
  REF_NOT_FOUND: 'REF_NOT_FOUND',
  REF_STALE: 'REF_STALE',
  FRAME_NOT_FOUND: 'FRAME_NOT_FOUND',
  FRAME_REF_INVALID: 'FRAME_REF_INVALID',
  FRAME_REF_MISMATCH: 'FRAME_REF_MISMATCH',
  PAGE_CHANGED: 'PAGE_CHANGED',
  ELEMENT_NOT_FOUND: 'ELEMENT_NOT_FOUND',
  IFRAME_ID_INVALID: 'IFRAME_ID_INVALID',
  ELEMENT_STATE_UNREADABLE: 'ELEMENT_STATE_UNREADABLE',
  ELEMENT_NOT_ACTIONABLE: 'ELEMENT_NOT_ACTIONABLE',
  IFRAME_ACTION_UNAUTHORIZED: 'IFRAME_ACTION_UNAUTHORIZED',
  ELEMENT_DISABLED: 'ELEMENT_DISABLED',
  ACTION_TARGET_MISMATCH: 'ACTION_TARGET_MISMATCH',
  FORM_ACTION_UNAUTHORIZED: 'FORM_ACTION_UNAUTHORIZED',
  FIELD_LABEL_MISSING: 'FIELD_LABEL_MISSING',
  FORM_SUBMIT_NOT_FOUND: 'FORM_SUBMIT_NOT_FOUND',
  FORM_FIELDS_UNAVAILABLE: 'FORM_FIELDS_UNAVAILABLE',
  FIELD_SENSITIVE_SKIPPED: 'FIELD_SENSITIVE_SKIPPED',
  FIELD_UNSUPPORTED_FILE_UPLOAD: 'FIELD_UNSUPPORTED_FILE_UPLOAD',
  FIELD_UNSAFE_HIDDEN: 'FIELD_UNSAFE_HIDDEN',
  FIELD_HONEYPOT_CANDIDATE: 'FIELD_HONEYPOT_CANDIDATE',
  FORM_VERIFY_FAILED: 'FORM_VERIFY_FAILED',
  SUBMIT_APPROVAL_DENIED: 'SUBMIT_APPROVAL_DENIED',
  SUBMIT_RESULT_UNKNOWN: 'SUBMIT_RESULT_UNKNOWN',
  NATIVE_DIALOG_UNSUPPORTED: 'NATIVE_DIALOG_UNSUPPORTED',
  FILL_RETRY_EXHAUSTED: 'FILL_RETRY_EXHAUSTED',
  FIELD_NOT_WRITABLE: 'FIELD_NOT_WRITABLE',
  FIELD_NOT_VISIBLE: 'FIELD_NOT_VISIBLE',
  APPROVAL_CONTEXT_STALE: 'APPROVAL_CONTEXT_STALE',
  CROSS_FORM_FILL_REJECTED: 'CROSS_FORM_FILL_REJECTED',
  SUBMIT_DISABLED: 'SUBMIT_DISABLED',
  SUBMIT_TARGET_NOT_READY: 'SUBMIT_TARGET_NOT_READY',
} as const;

export const ERROR_CODE_NUMBERS = Object.fromEntries(
  ERROR_CODE_DEFINITIONS.map((item) => [item.code, item.number])
) as Record<ErrorCode, number>;

export type ErrorCode = (typeof ERROR_CODE_DEFINITIONS)[number]['code'];
