export const SELECTION_MARKDOWN_MENU_ID = 'browserhelm-selection-to-markdown';
export const SELECTION_MARKDOWN_DOWNLOAD_MESSAGE = 'BH_SELECTION_MARKDOWN_DOWNLOAD';
export const SELECTION_TEXT_READ_MESSAGE = 'BH_SELECTION_TEXT_READ';
