export const EMPTY_STATE_REASONS = {
  NO_REFS_DETECTED: 'NO_REFS_DETECTED',
  NO_INTERACTIVE_ELEMENTS_DETECTED: 'NO_INTERACTIVE_ELEMENTS_DETECTED'
} as const;

export const UNSUPPORTED_REASONS = {
  FORM_FIELDS_READER_NOT_IMPLEMENTED: 'FORM_FIELDS_READER_NOT_IMPLEMENTED'
} as const;
