import { ERROR_CODES } from '../../shared/constants/error-codes';

export const TOOL_NOT_FOUND = ERROR_CODES.TOOL_NOT_FOUND;
export const TOOL_ARGS_INVALID = ERROR_CODES.TOOL_ARGS_INVALID;
export const TOOL_RESULT_INVALID = ERROR_CODES.TOOL_RESULT_INVALID;
export const TOOL_EXECUTION_FAILED = ERROR_CODES.TOOL_EXECUTION_FAILED;
export const TOOL_MODE_NOT_ALLOWED = ERROR_CODES.TOOL_MODE_NOT_ALLOWED;
