export const TOOL_NOT_FOUND = 'TOOL_NOT_FOUND';
export const TOOL_ARGS_INVALID = 'TOOL_ARGS_INVALID';
export const TOOL_RESULT_INVALID = 'TOOL_RESULT_INVALID';
export const TOOL_EXECUTION_FAILED = 'TOOL_EXECUTION_FAILED';
